import Head from "next/head";

export default function Home() {
  return (
    <div className="min-h-screen bg-white">
      <Head>
        <title>Tempo Next.js App</title>
        <meta name="description" content="Generated by Tempo" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold text-center mb-8">
          Welcome to Tempo Next.js!
        </h1>

        <div className="max-w-2xl mx-auto text-center">
          <p className="text-lg text-gray-600 mb-6">
            Your Next.js project is now configured for Tempo development.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-6 border rounded-lg">
              <h2 className="text-xl font-semibold mb-2">✅ Tempo DevTools</h2>
              <p className="text-gray-600">Installed and ready to use</p>
            </div>

            <div className="p-6 border rounded-lg">
              <h2 className="text-xl font-semibold mb-2">🛡️ Error Handling</h2>
              <p className="text-gray-600">Global error tracking configured</p>
            </div>

            <div className="p-6 border rounded-lg">
              <h2 className="text-xl font-semibold mb-2">📁 Git Ignore</h2>
              <p className="text-gray-600">Tempo files properly ignored</p>
            </div>

            <div className="p-6 border rounded-lg">
              <h2 className="text-xl font-semibold mb-2">🚀 Ready to Build</h2>
              <p className="text-gray-600">Start creating components!</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
